server:
  port: 8090


spring:
  datasource:
    username: "macros_web_app"
    password: "DUQa3Rc#!0@v" ##Enter your root password
    url: "jdbc:sqlserver://db-cbol-prod-managed.public.6b6f33eb6f05.database.windows.net:3342;database=MacrosWebApp;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true

#spring:
#  datasource:
#    username: "macroswebapp"
#    password: "M4cr0sw3b4pp*2022" ##Enter your root password
#    url: "jdbc:sqlserver://dwh.cbolivar.com:13143;databaseName=MacrosWebAppDev"
#    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
#  jpa:
#    hibernate.ddl-auto: none
#    generate-ddl: false
#    show-sql: false